language: python
python:
  - "3.7"
dist: xenial
sudo: false

branches:
  only:
    - master

install:
  - pip install python-docx
  - pip install chardet
  - pip install beautifulsoup4

cache:
  pip: true

# Use Taipai time
before_script:
  - export TZ=Asia/Taipei

# command to run tests
script:
  - python3 GlossProcessor.py https://drive.google.com/drive/folders/${BUDAI_RUKAI}

before_deploy:
  - rm -r *.sh *.py *.md *.txt Dockerfile .gitignore .travis.yml .dockerignore curl_download.log

deploy:
  provider: pages
  #target-branch: deploy
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
